### ISSUE TITLE
Document immediate encoding for addi

### ISSUE THREAD

**Issue by nick-knight** [riscv-non-isa/riscv-asm-manual#70]
Discussion on https://github.com/riscv/riscv-isa-manual/issues/740 concerned the following behaviors from the GNU assembler:
```
addi x0, x0, 0x800              # assembler error (illegal operand)
addi x0, x0, 0xfffff800         # assembles (immediate -2048) on RV32I but errors on RV64I
addi x0, x0, 0xfffffffffffff800 # assembles (immediate -2048) on both RV32I and RV64I
```
Can we explain this behavior? I'm happy to make a PR, but I'm not sure I fully understand the language rules myself.

The first case is apparently rejected because the [GNU assembler constant syntax](https://sourceware.org/binutils/docs/as/Integers.html#Integers) interprets `0x800` as `2048`, which is outside the range of `addi`'s immediate, a 12-bit signed integer, [-2048, 2047]. This behavior is arguably counterintuitive because `0x800` is a valid 12-bit `imm` field in an I-type instruction like `addi`. I think it's worth documenting this behavior (if it isn't already).

The second and third cases (and their decimal versions) are a bit more surprising.

**Comment by jim-wilson** [comment]
The assembler doesn't have typed constants.  So 0x800 is 0x00000800 which is not valid for addi.  RV32i has 32-bit constants, so 0xFFFFF800 is valid, and so is 0sFFFFFFFF FFFFF800.  RV64i has 64-bit constants, so 0x00000000fffff800 is not valid, and 0xFFFFFFFF FFFFF800 is valid.

Another way to look at this is to try decimal constants.  If someone writes "addi x0, x0, 4095" should we interpret that as "addi x0, x0, -1"?  That would just be silly.  Similarly, if someone writes "addi x0, x0, 0xfff" it would be wrong to treat that as -1 because 0xfff is 4095.

Another way to look at this is that humans tend to make mistakes when writing assembly language code, so we should not assume that something was intentional when it is ambiguous.  0x800 is ambiguous as it could be 2048 or -2048, so we don't accept it.  0xFFFFF800 is unambiguous for rv32i so we do accept it.

**Comment by nick-knight** [comment]
> Another way to look at this is to try decimal constants. If someone writes "addi x0, x0, 4095" should we interpret that as "addi x0, x0, -1"? That would just be silly. Similarly, if someone writes "addi x0, x0, 0xfff" it would be wrong to treat that as -1 because 0xfff is 4095.

Well, 
```
addi x0, x0, 4294965248
```
is interpreted as
```
addi x0, x0, -2048
```
on RV32I, and is illegal on RV64I. I think that's a bit silly too.

**Comment by nick-knight** [comment]
Perceived silliness aside, I'm not asking for any change in behavior. I'm just raising this issue to see if there is consensus around a case for documenting this behavior.

**Comment by jim-wilson** [comment]
rv32 has 32-bit constants.  So treating 4294965248 as -2048 is consistent with everything else.

**Comment by Hsiangkai** [comment]
llvm treat hexadecimal value as unsigned value. So, 0xfff is 4095 and 0xfffff800 is 4294965248. Both are out of range for addi.

**Comment by nick-knight** [comment]
I started a PR to address this then [stumbled across](https://github.com/riscv-non-isa/riscv-asm-manual/pull/71#issuecomment-921314467) what you just mentioned, that LLVM doesn't support this behavior. So my question really should have included, is GNU's behavior a language extension? Without an agreed-upon language spec, this is hard to answer.

**Comment by jim-wilson** [comment]
You can document the subset that both GNU and LLVM toolchains accept.
